version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nomoka_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
